language: python
python:
    - '3.6'
    - '3.6-dev'
    - '3.7-dev'
    - 'nightly'
install:
    - 'pip install -r dev_requirements.txt'
    - 'pip install -e .'
script:
    - pytest
after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then curl -H "Content-Type: application/json" --data \'{"build": true}\' -X POST "$DOCKER_TRIGGER_URL"; fi'
    - 'if [ -n "$TRAVIS_TAG" ]; then curl -H "Content-Type: application/json" --data \'{"build": true}\' -X POST "$DOCKER_TRIGGER_URL"; fi'
